version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: van79/backend:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: van79/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
